name: myapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.2
  lottie: ^3.1.0
  flutter_tts: ^3.6.3
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1 # 5.0.0 does not currently exist; latest as of June 2024 is 3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/loona_eyes_angry.json
    - assets/loona_eyes.json