name: myapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.2
  lottie: ^3.1.0
  flutter_tts: ^3.6.3
  http: ^1.1.0
  speech_to_text: ^7.0.0
  sentiment_dart: ^0.0.5
  vosk_flutter_2: ^1.0.5
  archive: ^3.4.0
  path_provider: ^2.1.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  google_sign_in: ^6.1.6
  flutterfire_cli: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1   # <-- Just ADD THIS line!

flutter_icons:   # <-- And THIS ICONS block is outside 'dev_dependencies'
  android: true
  ios: true
  image_path: "assets/icon/icon.png"   # <-- Make sure this file exists

flutter:
  uses-material-design: true
  assets:
    - assets/angry.json
    - assets/neutral.json
    - assets/models/vosk.zip
    - assets/splash/landscape/
    - assets/splash/portrait/
    - assets/google_logo.png